name: Deploy to Pages
on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'public/**'
      - 'vue.config.js'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build and Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CNAME: lolicon.dev
          BUILD_SCRIPT: yarn && yarn run build
